apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::176107463997:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-17K03NSCHPDNY
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::176107463997:role/UdacityFlaskDeployCBKubectlRole
      username: build

kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-25T16:47:52Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1756"
  uid: 232a1cd2-ceb2-449b-874e-f82e7f6fbcc0
